# Generated by Django 5.0.6 on 2024-09-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information_about_IT_LAB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='categorydocument',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Наименование на русском'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
