# Generated by Django 5.0.6 on 2024-10-08 06:02

import django.core.validators
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information_about_IT_LAB', '0002_alter_categorydocument_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='management/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])], verbose_name='Фотография')),
                ('fullName', models.CharField(max_length=255, verbose_name='ФИО')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Ваш номер телефона', max_length=31, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
    ]
