# Generated by Django 5.0.6 on 2024-10-08 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information_about_IT_LAB', '0003_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITLABRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='роль в it lab')),
                ('title_ru', models.CharField(max_length=255, verbose_name='роль на русском')),
            ],
        ),
        migrations.AlterField(
            model_name='management',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность в вузе'),
        ),
        migrations.AddField(
            model_name='management',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Information_about_IT_LAB.itlabrole', verbose_name='роль в IT LAB'),
        ),
    ]
