# Generated by Django 5.0.6 on 2024-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information_about_IT_LAB', '0004_itlabrole_alter_management_job_title_management_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='role',
        ),
        migrations.AlterField(
            model_name='management',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность в вузе (для преподавателей и руководства вуза)'),
        ),
        migrations.DeleteModel(
            name='ITLABRole',
        ),
    ]
