# Generated by Django 5.0.6 on 2024-10-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information_about_IT_LAB', '0005_remove_management_role_alter_management_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='job_title',
        ),
        migrations.AddField(
            model_name='management',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='роль в It lab (для студентов)'),
        ),
    ]
