# Generated by Django 5.0.6 on 2024-10-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information_about_IT_LAB', '0006_remove_management_job_title_management_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность в вузе (для преподавателей и руководства вуза)'),
        ),
    ]
