# Generated by Django 5.0.6 on 2024-08-17 12:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Наименование на русском')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='imagedb/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])], verbose_name='Изображение')),
                ('quote', models.CharField(blank=True, max_length=255, null=True, verbose_name='Любимая цитата')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователя',
            },
        ),
        migrations.CreateModel(
            name='ApplicationUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20, verbose_name='Группа')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('telegram', models.CharField(max_length=100, verbose_name='Ваш телеграмм')),
                ('descriptions', models.TextField(max_length=1000, verbose_name='Информация о вас')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('accepted', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Users.secions', verbose_name='Секция')),
            ],
        ),
    ]
