# Generated by Django 5.0.6 on 2024-08-22 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sections',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Users.secions', verbose_name='секция'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imagedb/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])], verbose_name='Изображение'),
        ),
    ]
