# Generated by Django 5.0.6 on 2024-08-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('brief_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('main_image', models.ImageField(upload_to='image/', verbose_name='Главное изображение')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('accepted', models.BooleanField(default=False, verbose_name='Одобрено')),
            ],
        ),
        migrations.CreateModel(
            name='Galery_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='NEWS.news')),
            ],
        ),
    ]
