# Generated by Django 5.0.6 on 2024-09-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0002_news_galery_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galery_News',
            new_name='Galery_Image_in_News',
        ),
    ]
